apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: RWdvci1kZ3A6Z2hwXzFLMU9Qeng0SHpJdks3SXl4emtrZUdhU1RQNVlUbDNNbEc1dg==
type: kubernetes.io/dockerconfigjson
